replicaCount: 1

image:
  repository: eckanas/rsschool_flask_app
  tag: 1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  # host: flask-app.${DOMAIN_NAME}
  host: flask-app.tuselis.lt

service:
  type: ClusterIP
  port: 8080 
