replicaCount: 1

image:
  repository: 033534701841.dkr.ecr.us-west-2.amazonaws.com/rsschool_flask_app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-creds

service:
  type: ClusterIP
  port: 8080 
