apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact-points
  namespace: monitoring
  labels:
    grafana_contact_point: "1"
data:
  contact-points.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: "RsSchool Contact Point"
        receivers:
          - uid: email_contact_point
            type: email
            settings:
              addresses: "rakauskased@gmail.com"
            disableResolveMessage: false
        isDefault: true 
