apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring
  labels:
    grafana_notification_policy: "1"
data:
  notification-policies.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: email_contact_point
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h 
