# jenkins-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - jenkins.example.com  # <-- Replace with your real domain
  #     secretName: jenkins-tls
  rules:
    - host: jenkins.example.com  # <-- Replace with your real domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
