grafana:
  extraVolumes:
    - name: cpu-alerts
      configMap:
        name: cpu-alerts-grafana-rules
  extraVolumeMounts:
    - name: cpu-alerts
      mountPath: /opt/bitnami/grafana/conf/provisioning/alerting
      readOnly: true
