grafana:
  extraVolumes:
    - name: rsschool-alerts
      configMap:
        name: rsschool-alerts-grafana-rules
    - name: contact-points
      configMap:
        name: grafana-contact-points
  extraVolumeMounts:
    - name: rsschool-alerts
      mountPath: /bitnami/grafana/conf/provisioning/alerting
      readOnly: true
    - name: contact-points
      mountPath: /bitnami/grafana/conf/provisioning/notifiers
      readOnly: true
