admin:
  user: admin
  password: admin123

grafana:
  replicaCount: 1
  extraConfiguration:
    smtp:
      enabled: true
      host: "email-smtp.us-west-2.amazonaws.com:587"
      user: "AKIAQPTWS6EIW746K4HN"
      password: "BCuiP3cz34vp/tEv30UAcnEqYwfarE9AaI3XLmDiSzV3"
      from_address: "grafana@tuselis.lt"
      from_name: "Grafana"
      skip_verify: false
      startTLS_policy: "Always"

ingress:
  enabled: true
  hostname: grafana.tuselis.lt
  path: /
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
