admin:
  password: admin123
  user: admin

grafana:
  replicaCount: 1

smtp:
  enabled: true
  host: "${SMTP_HOST}"
  user: "${SMTP_USER}"
  password: "${SMTP_PASSWORD}"
  fromAddress: "${SMTP_FROM_ADDRESS}"
  fromName: "Grafana"
  skipVerify: "false"

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hostname: grafana.${DOMAIN_NAME}
  path: /
  pathType: ImplementationSpecific
