# SonarQube project configuration for Flask app
sonar.projectKey=sqp_bb537af4a7bf56e1ec5cac6d855ade31e747cb36
sonar.projectName=Flask-App
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.inclusions=**/*.py 
