name: Manage Flask App Helm Chart

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Which Helm action to run'
        required: true
        default: 'install'
        type: choice
        options:
          - install
          - upgrade
          - remove

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_aws_account_id:    ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_GithubActionsRole: ${{ vars.GithubActionsRole }}
  TF_VAR_DOMAIN_NAMEe:      ${{ vars.DOMAIN_NAME }}

jobs:
  install:
    if: ${{ github.event.inputs.action == 'install' }}
    name: Install Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_aws_account_id }}:role/${{ env.TF_VAR_GithubActionsRole }}
          aws-region: us-west-2
      - name: Get K3s Config from SSM
        run: |
          aws ssm get-parameter \
            --name "/rsschool/k3s-yaml" \
            --with-decryption \
            --query "Parameter.Value" \
            --region us-west-2 \
            --output text > k3s-config.yaml
      - name: Set up Kubeconfig
        run: |
          if grep -q "127.0.0.1\|localhost" k3s-config.yaml; then
            sed -i "s/127.0.0.1/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
            sed -i "s/localhost/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
          fi
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Install Helm Chart
        run: |
          export KUBECONFIG=../../../k3s-config.yaml
          helm upgrade --install flask-app . \
            --set ingress.host=flask-app.${{ vars.DOMAIN_NAME }} 
        working-directory: K3S_Manifests/Mod3_Task5/flask_app_HelmChart

  upgrade:
    if: ${{ github.event.inputs.action == 'upgrade' }}
    name: Upgrade Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_aws_account_id }}:role/${{ env.TF_VAR_GithubActionsRole }}
          aws-region: us-east-2
      - name: Get K3s Config from SSM
        run: |
          aws ssm get-parameter \
            --name "/rsschool/k3s-yaml" \
            --with-decryption \
            --query "Parameter.Value" \
            --region us-west-2 \
            --output text > k3s-config.yaml
      - name: Set up Kubeconfig
        run: |
          if grep -q "127.0.0.1\|localhost" k3s-config.yaml; then
            sed -i "s/127.0.0.1/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
            sed -i "s/localhost/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
          fi
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Upgrade Helm Chart
        run: |
          export KUBECONFIG=../../../k3s-config.yaml
          helm upgrade --install flask-app . \
            --set ingress.host=flask-app.${{ vars.DOMAIN_NAME }} 
        working-directory: K3S_Manifests/Mod3_Task5/flask_app_HelmChart

  remove:
    if: ${{ github.event.inputs.action == 'remove' }}
    name: Remove Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_aws_account_id }}:role/${{ env.TF_VAR_GithubActionsRole }}
          aws-region: us-east-2
      - name: Get K3s Config from SSM
        run: |
          aws ssm get-parameter \
            --name "/rsschool/k3s-yaml" \
            --with-decryption \
            --query "Parameter.Value" \
            --region us-west-2 \
            --output text > k3s-config.yaml
      - name: Set up Kubeconfig
        run: |
          if grep -q "127.0.0.1\|localhost" k3s-config.yaml; then
            sed -i "s/127.0.0.1/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
            sed -i "s/localhost/${{ secrets.K3S_NODE_IP }}/g" k3s-config.yaml
          fi
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Uninstall Helm Chart
        run: |
          export KUBECONFIG=../../../k3s-config.yaml
          helm uninstall flask-app
        working-directory: K3S_Manifests/Mod3_Task5/flask_app_HelmChart 
