name: Destroy AWS, K3S infra, 

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Destroy K3S Workload"]
    types:
      - completed

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_aws_account_id:    ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_GithubActionsRole: ${{ vars.GithubActionsRole }}
      TF_VAR_public_key:        ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_private_key:       ${{ secrets.SSH_PRIVATE_KEY }}
      TF_VAR_vpc_cidr:          ${{ vars.vpc_cidr }}
      TF_VAR_ips_to_bastion:    ${{ vars.IPS_TO_BASTION }}
      TF_VAR_CERT_MANAGER_EMAIL: ${{ secrets.CERT_MANAGER_EMAIL }}
      TF_VAR_domain_name:       ${{ vars.domain_name }}
      TF_VAR_node_instance_profile: ${{ vars.node_instance_profile}}
    defaults:
      run:
        working-directory: Infrastructure

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4       
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.TF_VAR_aws_account_id }}:role/${{ env.TF_VAR_GithubActionsRole }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~> 1.12.0

      - name: Terraform Destroy Information
        run: |
          echo "## Terraform Destroy Process" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Starting infrastructure destruction...**" >> $GITHUB_STEP_SUMMARY
          echo "- AWS infrastructure will be destroyed" >> $GITHUB_STEP_SUMMARY
          echo "- Route53 DNS records will be automatically removed" >> $GITHUB_STEP_SUMMARY
          echo "- All resources will be cleaned up" >> $GITHUB_STEP_SUMMARY

      - name: Terraform init-destroy
        run: terraform init && terraform destroy -auto-approve
